import time
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

s=Service('C:/test/chromedriver.exe')
driver = webdriver.Chrome(service=s)
#открыть сайт и залогиниться
driver.get("https://qa.neapro.site/login/")
driver.set_window_size(1024, 600)
driver.maximize_window()
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").click()
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(1) input").send_keys("maluh_k@mail.ru")
driver.find_element(By.CSS_SELECTOR, ".fieldset:nth-child(2) input").send_keys("123456789")
driver.find_element(By.CSS_SELECTOR, ".btn").click()
time.sleep(3)
#открыть форму паспорта
driver.find_element(By.CSS_SELECTOR, ".form:nth-child(2) .document-tile:nth-child(1) > .document-name").click()

#заполнение формы
driver.find_element(By.ID, "surname").send_keys(Keys.CONTROL+"a")
driver.find_element(By.ID, "surname").send_keys(Keys.DELETE)
driver.find_element(By.ID,  "surname").send_keys("Бронер")
#driver.find_elements(By.ID, "surname").clear()
#driver.find_element(By.ID, "surname").send_keys("Малюх")
driver.find_element(By.ID, "name").send_keys(Keys.CONTROL+"a")
driver.find_element(By.ID, "name").send_keys(Keys.DELETE)
driver.find_element(By.ID,  "name").send_keys("Кристина")
#driver.find_elements(By.ID, "name").clear()
#driver.find_element(By.ID, "name").send_keys("Кристина")
driver.find_element(By.ID, "patronymic").send_keys(Keys.CONTROL+"a")
driver.find_element(By.ID, "patronymic").send_keys(Keys.DELETE)
driver.find_element(By.ID,  "patronymic").send_keys("Александровна")
#driver.find_element(By.ID, "patronymic").clear()
#driver.find_element(By.ID, "patronymic").send_keys("Александровна")
driver.find_element(By.NAME, "date").send_keys(Keys.CONTROL+"a")
driver.find_element(By.NAME, "date").send_keys(Keys.DELETE)
driver.find_element(By.NAME,  "date").send_keys("18.08.2000")
#driver.find_element(By.NAME, "date").clear()
#driver.find_element(By.NAME, "date").send_keys("16.09.1995")
#серия
driver.find_element(By.ID, "passportSeries").send_keys(Keys.CONTROL+"a")
driver.find_element(By.ID, "passportSeries").send_keys(Keys.DELETE)
driver.find_element(By.ID,  "passportSeries").send_keys("5656")
#driver.find_element(By.ID, "passportSeries").clear()
#driver.find_element(By.ID, "passportSeries").send_keys("660606")
driver.find_element(By.ID, "passportNumber").send_keys(Keys.CONTROL+"a")
driver.find_element(By.ID, "passportNumber").send_keys(Keys.DELETE)
driver.find_element(By.ID,  "passportNumber").send_keys("888999")
#driver.find_element(By.ID, "passportNumber").clear()
#driver.find_element(By.ID, "passportNumber").send_keys("555666")
driver.find_element(By.XPATH, '//*[@id="dateOfIssue"]/div/input').send_keys(Keys.CONTROL+"a")
driver.find_element(By.XPATH, '//*[@id="dateOfIssue"]/div/input').send_keys(Keys.DELETE)
driver.find_element(By.XPATH, '//*[@id="dateOfIssue"]/div/input').send_keys("06.09.2005")
#driver.find_element(By.XPATH, '//*[@id="dateOfIssue"]/div/input').clear()
#driver.find_element(By.XPATH, '//*[@id="dateOfIssue"]/div/input').send_keys("25.01.2022")
#од подр
driver.find_element(By.ID, "code").send_keys(Keys.CONTROL+"a")
driver.find_element(By.ID, "code").send_keys(Keys.DELETE)
driver.find_element(By.ID,  "code").send_keys("858585")
#driver.find_element(By.ID, "code").clear()
#driver.find_element(By.ID, "code").send_keys("555654")
driver.find_element(By.ID, "cardId").send_keys(Keys.CONTROL+"a")
driver.find_element(By.ID, "cardId").send_keys(Keys.DELETE)
driver.find_element(By.ID,  "cardId").send_keys("44455544477")
#driver.find_element(By.ID, "cardId").clear()
#driver.find_element(By.ID, "cardId").send_keys("44455544499")
driver.find_element(By.ID, "issued").send_keys(Keys.CONTROL+"a")
driver.find_element(By.ID, "issued").send_keys(Keys.DELETE)
driver.find_element(By.ID,  "issued").send_keys("РОВД Кемерово")
#driver.find_element(By.ID, "issued").clear()
#driver.find_element(By.ID, "issued").send_keys("РОВД г.Томск")
#driver.find_element(By.XPATH, '//*[@id="dateOfIssue"]/div/input').clear()
driver.find_element(By.XPATH, '//*[@id="address"]/div/div/input').send_keys(Keys.CONTROL+"a")
driver.find_element(By.XPATH, '//*[@id="address"]/div/div/input').send_keys(Keys.DELETE)
driver.find_element(By.XPATH, '//*[@id="address"]/div/div/input').send_keys("г. Стрежевой")
#driver.find_element(By.XPATH, '//*[@id="address"]/div/div/input').clear()
#driver.find_element(By.XPATH, '//*[@id="address"]/div/div/input').send_keys("г Томск")
driver.find_element(By.ID, "phone").send_keys(Keys.CONTROL+"a")
driver.find_element(By.ID, "phone").send_keys(Keys.DELETE)
driver.find_element(By.ID,  "phone").send_keys("5555559988")
#driver.find_element(By.ID, "phone").clear()
#driver.find_element(By.ID, "phone").send_keys("9999995544")
driver.find_element(By.CSS_SELECTOR, "#__layout > div > div.content-wrapper > div > div > div.content-page > div > div > div.form.passport-form.document-form > div.body > div.buttons > button.btn.fill").click()
